version: '3.9'

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mhabiba/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mhabiba/data/wordpress
      o: bind

networks:
  inception:
    name : inception

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    expose:
      - 9000
    restart: always
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - 3306
    restart: always
